name: Kube-News CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch: 
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build Kube-News
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./Dockerfile
          push: true
          tags: |
            rodrigototy/kube-news-app:v2
            rodrigototy/kube-news-app:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Kube-News
        run: echo "Deploy Kube-News"
